### ISSUE TITLE
[Tracker]: clearly standardize vim's C coding style

### ISSUE THREAD

**Issue by saccarosium** [vim/vim#15930]
This is a tracking issue for clearly standardize vim's C coding|formatting style.

### The problem

As stated in #15789 the current situation for the C source code is really messy.

There current "rules" are very loose and they need manual intervention from the maintainers to maintain.

### Solution

Decide a clear set of styles and conventions to enforce automatically on the source. This will simply makes life easier both the current and future maintainers.

### Steps

- [x] Agreeing on best practices and code conventions
  - [x] https://github.com/vim/vim/issues/15932
  - [x] https://github.com/vim/vim/pull/15967
- [ ] Choosing a formatter
  - [x] https://github.com/vim/vim/pull/16019
  - [ ] integrate the formatter (integration with `formatprg`/plugin, CI, etc)
